/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agendabd;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 1578240
 */
public class Emprestimo extends javax.swing.JFrame {

    /**
     * Creates new form Emprestimo
     */
    public Emprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caixaContato = new javax.swing.JComboBox();
        caixaCatalogo = new javax.swing.JComboBox();
        botaoGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("EMPRÉSTIMO");

        jLabel2.setText("Contato:");

        jLabel3.setText("Catalogo:");

        botaoGravar.setText("GRAVAR");
        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caixaContato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caixaCatalogo, 0, 291, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoGravar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caixaContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caixaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        abrirContato();
        abrirCatalogo();
    }//GEN-LAST:event_formWindowOpened

    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarActionPerformed
        //substring p pegar só os 4 digitos
        
        String idcontato = 
        caixaContato.getSelectedItem()
                .toString().substring(0,4);
                
        String idcatalogo = 
        caixaCatalogo.getSelectedItem()
                .toString().substring(0,4);
        
        String comando1 = 
        "INSERT INTO emprestimo"
        + "(idcontato,idcatalogo,datasaida) "
        + "VALUES (?,?,CURDATE())";
        
       
        String comando2 = 
        "UPDATE catalogo SET emprestado = 1 " +
        "WHERE id = ?";
        
        try{
            Connection conn = Conexao.getConexao();
            
            PreparedStatement ps1 = 
                    conn.prepareStatement(comando1);
            
            ps1.setString(1, idcontato);
            ps1.setString(2, idcatalogo);
            ps1.execute();
            
            PreparedStatement ps2 = 
                    conn.prepareStatement(comando2);
            ps2.setString(1, idcatalogo);
            ps2.execute();
            
            JOptionPane.showMessageDialog(null,
                    "GRAVADO COM SUCESSO");
            abrirCatalogo();
        }catch(Exception e){
            e.printStackTrace();
        }//fim-catch
        
    }//GEN-LAST:event_botaoGravarActionPerformed

    
    void abrirContato(){
        Connection conn = Conexao.getConexao();
        
        String comando = 
        "SELECT * FROM contato " +
        "ORDER BY nome";
        
        try{
            PreparedStatement ps =
                    conn.prepareStatement(comando);
            
            ResultSet res = ps.executeQuery();
            
            caixaContato.removeAllItems();
            
            while(res.next()){
                caixaContato.addItem(
                String.format("%04d", res.getInt("id")) 
                + " - " +
                res.getString("nome"));
            }//fim-while
            
        }catch(Exception e){
            e.printStackTrace();
        }//fim-catch
    }//fim-abrirContato
    
    
    void abrirCatalogo(){
        
        Connection conn = Conexao.getConexao();
        
        String comando = 
        "SELECT * FROM catalogo WHERE emprestado = 0 " +
        "ORDER BY tipo, titulo";
        
        try{
            PreparedStatement ps =
                    conn.prepareStatement(comando);
            
            ResultSet res = ps.executeQuery();
            
            caixaCatalogo.removeAllItems();
            
            while(res.next()){
                caixaCatalogo.addItem(
                String.format("%04d", res.getInt("id")) 
                + " - " +
                res.getString("tipo") + " - " +
                res.getString("titulo"));
            }//fim-while
            
        }catch(Exception e){
            e.printStackTrace();
        }//fim-catch
    }//fim-abrirCatalogo
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGravar;
    private javax.swing.JComboBox caixaCatalogo;
    private javax.swing.JComboBox caixaContato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
